import {StyleSheet, Dimensions} from 'react-native';
const {width, height} = Dimensions.get('window');
import {FONT} from '@/src/constants/styles/font/default-font';

export const FriendsProfileScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  logoSection: {
    alignItems: 'center',
    flexDirection: 'row',
    paddingVertical: height * 0.02,
  },
  logoInfo: {
    flexDirection: 'row',
  },
  logoImage: {
    width: width * 0.2,
    height: height * 0.06,
    left: width * 0.05,
    resizeMode: 'contain',
  },
  upperSection: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    padding: height * 0.06,
    backgroundColor: '#86C0AE',
  },
  profileInfo: {
    flexDirection: 'row',
    flex: 1,
    position: 'absolute',
    left: width * 0.07,
  },
  profileImage: {
    width: width * 0.22,
    height: width * 0.22,
    marginTop: height * 0.05,
    left: width * 0.02,
    borderRadius: (width * 0.25) / 2,
  },
  profileTextContainer: {
    marginLeft: width * 0.04,
    marginTop: height * 0.03,
    flexDirection: 'row',
    alignItems: 'center',
  },
  nickname: {
    fontSize: width * 0.035,
    color: '#009499',
    marginLeft: width * 0.025,
    fontFamily: `${FONT}`,
    fontWeight: '900',
  },
  username: {
    fontSize: width * 0.05,
    fontFamily: `${FONT}`,
    fontWeight: '900',
    color: '#333',
    marginLeft: width * 0.025,
    marginTop: -height * 0.005,
  },
  badgeContainer: {
    padding: height * 0.025,
    marginTop: 25,
    marginLeft: -50,
  },
  badges: {
    flexDirection: 'row',
    backgroundColor: 'white',
    padding: width * 0.025,
    borderRadius: width * 0.015,
    alignSelf: 'flex-start',
    alignItems: 'center',
  },
  badgeText: {
    fontWeight: 'bold',
    fontSize: width * 0.035,
    marginLeft: width * 0.015,
    fontFamily: `${FONT}`,
    color: '#838F8F',
    marginBottom: height * 0.003,
    alignSelf: 'flex-start',
  },
  badge: {
    width: width * 0.09,
    height: width * 0.09,
    marginRight: width * 0.02,
    resizeMode: 'contain',
  },
  moreButton: {
    color: '#009499',
    flexDirection: 'row',
    alignItems: 'center',
  },
  moreText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#0D9488',
    marginLeft: 5,
    fontFamily: `${FONT}`,
  },
  moreImage: {
    marginTop: 8,
    marginLeft: 15,
    marginRight: 5,
    marginBottom: 5,
  },
  friendMessageSection: {
    marginTop: height * 0.025,
    paddingVertical: height * 0.01,
    paddingHorizontal: width * 0.04,
    borderRadius: width * 0.02,
    marginLeft: width * 0.01,
    position: 'relative',
    alignSelf: 'flex-start',
  },
  sectionTitle: {
    fontWeight: 'bold',
    fontSize: width * 0.035,
    marginLeft: width * 0.01,
    color: '#838F8F',
    fontFamily: `${FONT}`,
  },
  friendMessageButton: {
    backgroundColor: '#5AA6A8',
    paddingVertical: height * 0.008,
    paddingHorizontal: width * 0.03,
    borderRadius: width * 0.015,
    borderBottomLeftRadius: 0,
    marginTop: height * 0.012,
    alignSelf: 'flex-start',
  },
  friendMessageText: {
    color: '#FFFFFF',
    fontSize: width * 0.04,
    fontFamily: `${FONT}`,
    fontWeight: '700',
  },
  infoText: {
    fontSize: width * 0.025,
    color: '#009499',
    marginTop: height * 0.012,
    fontFamily: `${FONT}`,
    fontWeight: '700',
  },
  calendarContainer: {
    marginTop: height * 0.025,
    paddingHorizontal: width * 0.04,
  },
  iconAndTextContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: height * 0.002,
  },
  setiIcon: {
    width: width * 0.03,
    height: width * 0.03,
    resizeMode: 'contain',
    marginRight: width * 0.015,
  },
  activeText: {
    fontFamily: `${FONT}`,
    color: '#009499',
    fontSize: width * 0.03,
  },
  successMessage: {
    fontSize: width * 0.035,
    color: '#28a745',
    fontFamily: `${FONT}`,
    fontWeight: '700',
    marginTop: height * 0.01,
  },
});
