export const ILLUSTRATIONS = {
  BANNER_IMAGE1: '@/assets/images/illustration/bannerImage1.png',
  BANNER_IMAGE2: '@/assets/images/illustration/bannerImage2.png',
  BANNER_IMAGE3: '@/assets/images/illustration/bannerImage3.png',
  BANNER_IMAGE4: '@/assets/images/illustration/bannerImage4.png',
  FREEZE: '@/assets/images/illustration/freeze.png',
  INTRO: '@/assets/images/illustration/intro.png',
  INTRO_FOUR: '@/assets/images/illustration/introFour.png',
  INTRO_THREE: '@/assets/images/illustration/introThree.png',
  INTRO_TWO: '@/assets/images/illustration/introTwo.png',
  JANDI1: '@/assets/images/illustration/jandi1.png',
  JANDI2: '@/assets/images/illustration/jandi2.png',
  LOADER: '@/assets/images/illustration/loader.gif',
  LOGO: '@/assets/images/illustration/logo.png',
  PROFILE_IMAGE1: '@/assets/images/illustration/profileImage1.png',
  PROFILE_IMAGE2: '@/assets/images/illustration/profileImage2.png',
  PROFILE_IMAGE3: '@/assets/images/illustration/profileImage3.png',
  PROFILE_IMAGE4: '@/assets/images/illustration/profileImage4.png',
  TYPE_ONE: '@/assets/images/illustration/typeOne.png',
  TYPE_THREE: '@/assets/images/illustration/typeThree.png',
  TYPE_TWO: '@/assets/images/illustration/typeTwo.png',
};
