export const ILLUSTRATIONS = {
  BANNER_IMAGE1: require('@/assets/images/illustration/bannerImage1.png'),
  BANNER_IMAGE2: require('@/assets/images/illustration/bannerImage2.png'),
  BANNER_IMAGE3: require('@/assets/images/illustration/bannerImage3.png'),
  BANNER_IMAGE4: require('@/assets/images/illustration/bannerImage4.png'),
  FLOWER_GRASS: require('@/assets/images/illustration/flowerNgrass.png'),
  FREEZE: require('@/assets/images/illustration/freeze.png'),
  INTRO: require('@/assets/images/illustration/intro.png'),
  INTRO_FOUR: require('@/assets/images/illustration/introFour.png'),
  INTRO_THREE: require('@/assets/images/illustration/introThree.png'),
  INTRO_TWO: require('@/assets/images/illustration/introTwo.png'),
  JANDI1: require('@/assets/images/illustration/jandi1.png'),
  JANDI2: require('@/assets/images/illustration/jandi2.png'),
  LOADER: require('@/assets/images/illustration/loader.gif'),
  LOGO: require('@/assets/images/illustration/logo.png'),
  PROFILE_IMAGE1: require('@/assets/images/illustration/profileImage1.png'),
  PROFILE_IMAGE2: require('@/assets/images/illustration/profileImage2.png'),
  PROFILE_IMAGE3: require('@/assets/images/illustration/profileImage3.png'),
  PROFILE_IMAGE4: require('@/assets/images/illustration/profileImage4.png'),
  TYPE_ONE: require('@/assets/images/illustration/typeOne.png'),
  TYPE_TWO: require('@/assets/images/illustration/typeTwo.png'),
  TYPE_THREE: require('@/assets/images/illustration/typeThree.png'),
};
