name: Version Bump and GitHub Release

on:
  push:
    branches:
      - development

jobs:
  version-bump:
    name: Version bump of app
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install yarn
        run: npm install -g yarn

      - name: Install node_modules
        run: npm ci

      - name: Version bump and publish release
        uses: nabeel-shakeel/react-native-version@main
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          supported_parameters: '{"tag-prefix":"v", "tag-suffix":"-staged", "automatic_release_tag":"latest_release"}'